### ISSUE TITLE
Naked People Everywhere/CFP Barbershop Clothes Make People Naked

### ISSUE THREAD

**Issue by unholycheese666** [ElTyranos/CommunityFlavorPack#128]
I've been running CFP with no issues for a while until now, but after the Fate of Iberia update I've been having the issue described above. The game will sometimes also crash shortly after startup. This happens when CFP is the only mod running and I've tried uninstalling and reinstalling it about 5-10 times.
![Screenshot 2022-06-12 204833](https://user-images.githubusercontent.com/107375514/173261027-ccec3f4a-e796-4481-a914-0890bf3a8e93.png)

**Comment by ElTyranos** [comment]
Please post your error.log

**Comment by unholycheese666** [comment]
[error.log](https://github.com/ElTyranos/CommunityFlavorPack/files/8896200/error.log)

**Comment by ElTyranos** [comment]
You have several missing files both on the mod (scripted triggers) and vanilla (missing models).

e.g.
`[23:43:32][virtualfilesystem.cpp:440]: Could not find texture due to 'VFSOpen Error: gfx/models/portraits/attachments/female_headgear/secular/fp2_christian/high_nobility_01/female_headgear_secular_fp2_iberian_christian_high_nobility_01_properties.dds not found'`
`[23:43:40][pdx_persistent_reader.cpp:238]: Error: "Unknown trigger type: cfp_portrait_norse_clothing_trigger, near line: 37" in file: "gfx/portraits/portrait_modifiers/01_cloaks.txt" near line: 41`

You also run catholic trinity, which is not updated to Fate of Iberia yet. It is likely the source of your problem.

I advise you to disable this mod, verify your game files and likely to do option 2 here : https://wiki.communityflavorpack.com/troubleshooting/force-reinstall
`[23:43:40][pdx_persistent_reader.cpp:238]: Error: "Unknown trigger type: CatholicTrinityCardinalOrAntiPopeTrigger, near line: 4443" in file: "gfx/portraits/portrait_modifiers/01_clothes.txt" near line: 4444`
