### ISSUE TITLE
Anglo-saxon Helm (sutton hoo) available for non-combat women and viking helmet (vendel) missing mesh.

### ISSUE THREAD

**Issue by voy178** [ElTyranos/CommunityFlavorPack#37]
As the image suggests, there is a helmet that doesn't work currently. On the same picture, you can see a woman who is neither knight nor marshal (nor landed if it matters) wearing a helmet as default outfit which is not quite right (might be related to the Anglo-Saxon Helm or just women in general as I've seen women wearing helmets before despite them being non-combatant in previous updates). 

![20201008235116_1](https://user-images.githubusercontent.com/44323473/95517690-c7c75680-09c1-11eb-97ae-297051292001.jpg)

Thank you for fixing it so that war gear is only worn in war, it both works and looks great now!

**Comment by voy178** [comment]
The plot thickens as another Anglo-Saxon king uses the helmet instead of a crown during peacetime.

![20201009155544_1](https://user-images.githubusercontent.com/44323473/95591684-eff99880-0a47-11eb-9e0d-798bc7e8ba62.jpg)

**Comment by ElTyranos** [comment]
The (sutton hoo) helmet is believed to be part of proto-anglo-saxon kings' regalia. It's believed rulers did use helmets during ceremonies before Crowns.

The original one was fit for battle but it's unknown if it actually saw combat. Yet historians have reasons to think it was used at court to impress people. Imagine being a peasant coming to the king to ask for justice, and the guy has a loud voice behind a scary mask, well, you'd shit in your pants and that's the point.

Regarding the random usage of regalia / war regalia assets by knights and commoners, I will investigate.

**Comment by ElTyranos** [comment]
Fixed what was actually an issue of  your repport.

Regarding the Vendel viking helmet I am not able to reproduce. I recommend you to delete your mod files and redownload them so it refreshes.  The issue is old, was fixed a while ago and was caused by casing mismatch. It's likely your local files were not updating because the casing change was undetected / ignored.

![image](https://user-images.githubusercontent.com/6755711/95656782-e7b96000-0b10-11eb-9290-a81f0f60f379.png)
